# Generated by Django 5.0 on 2023-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_remove_details_email_remove_details_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='city_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='country_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='state_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
