# Generated by Django 5.0 on 2023-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_alter_details_city_name_alter_details_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='image',
            field=models.ImageField(default='', upload_to='app/img'),
        ),
    ]
